enableTelemetry: false

packageExtensions:
  "@prisma/client@*":
    dependencies:
      .prisma: "link:./prisma::locator=machat-prisma@workspace:."
  eslint-config-airbnb-typescript@*:
    dependencies:
      "@typescript-eslint/parser": "*"
    peerDependencies:
      "@typescript-eslint/parser": "*"
      eslint: "*"
      eslint-plugin-import: "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  fastify-cookie@*:
    peerDependencies:
      fastify: "*"
  fastify-cors@*:
    peerDependencies:
      fastify: "*"
  fastify-session@*:
    peerDependencies:
      fastify: "*"
  mercurius@*:
    peerDependencies:
      fastify: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.3.3.cjs
